name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Замените на нужную версию JDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success() # Deploy only if it's the main branch and the build succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Remote Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Используем секреты GitHub для хранения SSH-ключа
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key user@your-server-address "cd /path/to/your/app && git pull && mvn clean install && java -jar your-app.jar"
