name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Используем секреты GitHub для хранения Heroku API Key
        run: |
          echo "machine api.heroku.com" >> ~/.netrc
          echo "  login your-email@example.com" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login your-email@example.com" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/your-heroku-app.git
          git push heroku main
