name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Замените на нужную версию JDK
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success() # Deploy only if it's the main branch and the build succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Remote Server
        run: |
          ssh user@your-server "cd /path/to/your/app && git pull && mvn clean install && java -jar your-app.jar"
