name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' 

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build .

      - name: Run tests
        run: go test ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success() # Deploy only if it's the main branch and the build succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Remote Server
        run: |
          ssh user@your-server "cd /path/to/your/app && git pull && go build . && ./your-app"
